spring:
  datasource:
    url: jdbc:mysql://120.79.143.66:3306/user_center
    hikari:
      username: root
      password: WSQlight
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 指定namespace
        # namespace: 56116141-d837-4d15-8842-94e153bb6cfb
        # NJ
        # 指定集群名称
        cluster-name: BJ
        # 定义元数据， 扩展Ribbon-基于元数据的版本控制
#        metadata:
#          instance: c
#          haha: hehe
#          version: v1
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        # 消费消息
        input:
          destination: add-bonus
          group: binder-group

  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-center
#  zipkin:
#    base-url: http://localhost:9411/
#    discoveryClientEnabled: false
#  sleuth:
#    sampler:
#      # 抽样率，默认是0.1（10%）
#      probability: 1.0
  main:
    allow-bean-definition-overriding: true
server:
  port: 8082
logging:
  level:
    com.alibaba.nacos: error
    org.springframework.cloud.sleuth: debug
#jwt:
#  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
#  # 有效期，单位秒，默认2周
#  expire-time-in-second: 1209600
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

dubbo:
  scan:
    # 指定 Dubbo 服务实现类的扫描基准包
    base-packages: com.itmuch.usercenter.service.dubbo
  protocol:
    # Dubbo服务暴露的协议配置，其中子属性name为协议名称，port为协议端口（-1 表示自增端口，从 20880 开始）
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://127.0.0.1